// Code generated by protoc-gen-go. DO NOT EDIT.
// source: myservice/myservice.proto

/*
Package myservice is a generated protocol buffer package.

It is generated from these files:
	myservice/myservice.proto

It has these top-level messages:
	Arg
	Output
*/
package myservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type Arg struct {
	Args []string `protobuf:"bytes,1,rep,name=args" json:"args,omitempty"`
}

func (m *Arg) Reset()                    { *m = Arg{} }
func (m *Arg) String() string            { return proto.CompactTextString(m) }
func (*Arg) ProtoMessage()               {}
func (*Arg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Arg) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

// The response message containing the greetings
type Output struct {
	Retcode int32  `protobuf:"varint,1,opt,name=retcode" json:"retcode,omitempty"`
	Stdout  string `protobuf:"bytes,2,opt,name=stdout" json:"stdout,omitempty"`
	Stderr  string `protobuf:"bytes,3,opt,name=stderr" json:"stderr,omitempty"`
}

func (m *Output) Reset()                    { *m = Output{} }
func (m *Output) String() string            { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()               {}
func (*Output) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Output) GetRetcode() int32 {
	if m != nil {
		return m.Retcode
	}
	return 0
}

func (m *Output) GetStdout() string {
	if m != nil {
		return m.Stdout
	}
	return ""
}

func (m *Output) GetStderr() string {
	if m != nil {
		return m.Stderr
	}
	return ""
}

func init() {
	proto.RegisterType((*Arg)(nil), "myservice.Arg")
	proto.RegisterType((*Output)(nil), "myservice.Output")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MyService service

type MyServiceClient interface {
	// Sends a greeting
	Hello(ctx context.Context, in *Arg, opts ...grpc.CallOption) (*Output, error)
	Goodbye(ctx context.Context, in *Arg, opts ...grpc.CallOption) (*Output, error)
}

type myServiceClient struct {
	cc *grpc.ClientConn
}

func NewMyServiceClient(cc *grpc.ClientConn) MyServiceClient {
	return &myServiceClient{cc}
}

func (c *myServiceClient) Hello(ctx context.Context, in *Arg, opts ...grpc.CallOption) (*Output, error) {
	out := new(Output)
	err := grpc.Invoke(ctx, "/myservice.MyService/Hello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myServiceClient) Goodbye(ctx context.Context, in *Arg, opts ...grpc.CallOption) (*Output, error) {
	out := new(Output)
	err := grpc.Invoke(ctx, "/myservice.MyService/Goodbye", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MyService service

type MyServiceServer interface {
	// Sends a greeting
	Hello(context.Context, *Arg) (*Output, error)
	Goodbye(context.Context, *Arg) (*Output, error)
}

func RegisterMyServiceServer(s *grpc.Server, srv MyServiceServer) {
	s.RegisterService(&_MyService_serviceDesc, srv)
}

func _MyService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Arg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/myservice.MyService/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServiceServer).Hello(ctx, req.(*Arg))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyService_Goodbye_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Arg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServiceServer).Goodbye(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/myservice.MyService/Goodbye",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServiceServer).Goodbye(ctx, req.(*Arg))
	}
	return interceptor(ctx, in, info, handler)
}

var _MyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "myservice.MyService",
	HandlerType: (*MyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _MyService_Hello_Handler,
		},
		{
			MethodName: "Goodbye",
			Handler:    _MyService_Goodbye_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "myservice/myservice.proto",
}

func init() { proto.RegisterFile("myservice/myservice.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x8f, 0xc1, 0x0a, 0x82, 0x40,
	0x10, 0x86, 0xdb, 0x4c, 0x65, 0xe7, 0x10, 0x34, 0x87, 0x58, 0x3b, 0x89, 0x27, 0x0f, 0x61, 0x50,
	0x4f, 0xe0, 0xa9, 0x2e, 0x11, 0x6c, 0x4f, 0x90, 0x3a, 0x88, 0x60, 0xac, 0x8c, 0x6b, 0xe0, 0xdb,
	0x07, 0x6a, 0xd6, 0xb1, 0xdb, 0xff, 0x7d, 0x0c, 0xcc, 0xff, 0x43, 0xf0, 0xec, 0x5b, 0xe2, 0x57,
	0x95, 0xd3, 0x61, 0x4e, 0x49, 0xc3, 0xc6, 0x1a, 0x94, 0xb3, 0x88, 0x02, 0x70, 0x52, 0x2e, 0x11,
	0x61, 0xf5, 0xe0, 0xb2, 0x55, 0x22, 0x74, 0x62, 0xa9, 0x87, 0x1c, 0x69, 0xf0, 0x6e, 0x9d, 0x6d,
	0x3a, 0x8b, 0x0a, 0x7c, 0x26, 0x9b, 0x9b, 0x82, 0x94, 0x08, 0x45, 0xec, 0xea, 0x0f, 0xe2, 0x16,
	0xbc, 0xd6, 0x16, 0xa6, 0xb3, 0x6a, 0x19, 0x8a, 0x58, 0xea, 0x89, 0x26, 0x4f, 0xcc, 0xca, 0x99,
	0x3d, 0x31, 0x1f, 0x2b, 0x90, 0xd7, 0xfe, 0x3e, 0xfe, 0xc6, 0x3d, 0xb8, 0x17, 0xaa, 0x6b, 0x83,
	0xeb, 0xe4, 0xdb, 0x30, 0xe5, 0x72, 0xb7, 0xf9, 0xe1, 0xb1, 0x42, 0xb4, 0xc0, 0x04, 0xfc, 0xb3,
	0x31, 0x45, 0xd6, 0xd3, 0x5f, 0xf7, 0x99, 0x37, 0x6c, 0x3d, 0xbd, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x7b, 0x4c, 0xcc, 0x89, 0x08, 0x01, 0x00, 0x00,
}
